### ISSUE TITLE
FirstMessage no longer working

### ISSUE THREAD

**Issue by mocchimon** [Sehelitar/Kick.bot#16]
Hi,
I have the bot setup to automatically shoutout people with their first message sent in chat. the latest update no longer allows it to work for some reason.
![image](https://github.com/Sehelitar/Kick.bot/assets/10341644/98fcde30-ee0f-41ab-a728-88668ead3af0)

**Comment by Sehelitar** [comment]
Hey! 👋
Kick doesn't implement a "first message" logic in chat for now, so this field has always been set to ``false``, as seen here : https://github.com/Sehelitar/Kick.bot/blob/c9a0c02593386bb5e9bcbcbf243a82309c235055/BotEventListener.cs#L136

Tracking this would require to store every users ids in a database, in a more efficient way than in SB Global Vars.
Another way to store this would have been the ``SetUserVar`` method, which is perfect for this use-case ... but this method will be removed from SB soon ... 😵‍💫
For now, you could use temporary Global Vars for this (under Core => Globals) if you know how to do it.

I will keep that in mind for a future update. 👍

**Comment by mocchimon** [comment]
strange this was working a few updates ago. Appreciate the temp fix. I'll give it a try

**Comment by Sehelitar** [comment]
Hey! 👋
So, the ``firstMessage`` argument is now usable in this new pre-release : https://github.com/Sehelitar/Kick.bot/releases/tag/v0.3.7
I didn't have time to test everything properly, so this is flagged as a pre-release for now.
Feel free to try it out and tell me if you find anything weird 😅

**Comment by mocchimon** [comment]
Appreciate it! so far I'm having trouble finding a way to reset the firstmessage to continue testing. Other than that my setup is sort of working. The 2nd message isn't being sent for some reason

**Comment by Sehelitar** [comment]
The database can be found in ``data\kick-ext.db`` in your bot's installation folder.
You can avoid a full restart by doing these 3 steps : ``Unload``, delete the file, ``Compile``.
Both actions can be found here : 
<img width="319" alt="Double break" src="https://github.com/Sehelitar/Kick.bot/assets/1716704/3ac98288-ceaa-48a3-92a9-01ccce37ad61">

As for your second message, this ``If`` sub-action blocks it : 
<img width="406" alt="Duplicate message" src="https://github.com/Sehelitar/Kick.bot/assets/1716704/c54be6e8-5ca1-4c2a-8218-0d13afe80600">
You also set the ``message`` argument twice right after that, the second value will overwrite the first.

**Comment by mocchimon** [comment]
After unloading, compiling and disabling the line it still doesn't work
![image](https://github.com/Sehelitar/Kick.bot/assets/10341644/8688cab1-1050-4dc2-9533-68bd80194238)
