### ISSUE TITLE
Triggers + chat command + send message

### ISSUE THREAD

**Issue by JotaRodriii** [Sehelitar/Kick.bot#17]
Good evening,

I just downloaded and installed the kick bot on streamer.bot, everything ok.

I have a problem and that is that I can't assign a chat command for example !test and launch a message in the kick chat.

Attached is a screenshot where I can't change the trigger to !test, it always stays in Any.

![image](https://github.com/Sehelitar/Kick.bot/assets/149625498/a37d7d3a-2aa3-4740-b143-fd3870cf72c2)

Could you help me please?

**Comment by Sehelitar** [comment]
Hey! 👋

When you add a trigger, you should find your commands under ``Custom`` => ``Kick`` => ``Commands``.
If they are missing and you just created them, remember to click on the ``Save`` button before adding new triggers on your actions.
Only then they will appear in the menu, and you should get something like this : 

<img width="307" alt="image" src="https://github.com/Sehelitar/Kick.bot/assets/1716704/38312127-4ca9-41a8-b76d-7f193be1c89b">

**Comment by JotaRodriii** [comment]
Good morning,

Thank you for your prompt reply.

I have several commands created for Twitch. Should I create a special one for kick? What format should it be?

Whenever I add as a trigger custom-kick-command I only get the Any and not the commands I have for Twitch.

On a side note, I am correctly connected to my kick channel as I get the Windows notification every time I start streamer.bot.

Could you please show me some kick command created and how it appears as a trigger?

Thank you very much for the help

**Comment by Sehelitar** [comment]
I just updated the installation guide and added a section about commands usage : 
https://github.com/Sehelitar/Kick.bot/wiki/Installation#createuse-commands

**Comment by JotaRodriii** [comment]
Thanks! Well done! It's ok!
