### ISSUE TITLE
System.IO.DirectoryNotFoundException

### ISSUE THREAD

**Issue by Ranktotop** [Sehelitar/Kick.bot#23]
If i click compile (after adding the two dll-files), i'm getting "compiled successfully!". However, if i click ok, Streamer.bot crashes.

After checking the log i'm seeing:
[2024-01-01 15:03:35.807 DBG] Exception : System.IO.DirectoryNotFoundException: Ein Teil des Pfades "C:\Windows\system32\data\kick-ext.db" konnte nicht gefunden werden.
   bei System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   bei System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   bei System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   bei LiteDB.Engine.FileStreamFactory.GetStream(Boolean canWrite, Boolean sequencial)
   bei System.Lazy`1.CreateValue()
   bei System.Lazy`1.LazyInitValue()
   bei LiteDB.Engine.DiskService..ctor(EngineSettings settings, Int32[] memorySegmentSizes)
   bei LiteDB.Engine.LiteEngine..ctor(EngineSettings settings)
   bei LiteDB.ConnectionString.CreateEngine()
   bei LiteDB.LiteDatabase..ctor(ConnectionString connectionString, BsonMapper mapper)
   bei Kick.Bot.BotClient..ctor()
   bei v0d21e75be0042b39bc129eb01b72ea8.CPHInline.<<Authenticate>b__4_0>d.MoveNext()

[Kick] Extension is shuting down
[2024-01-01 15:03:39.456 DBG] Actions :: Time to save 7,6334ms
[2024-01-01 15:03:39.563 FTL] Fatal UI Exception
System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
   bei Kick.Bot.BotClient.Finalize()

I ran the bot with administrator privileges..
![kick](https://github.com/Sehelitar/Kick.bot/assets/42238940/25580757-a783-4d2f-848d-3e50588b962b)

Did anyone else got this error?

**Comment by Sehelitar** [comment]
Hi!

Streamer.bot should **NEVER** run with administrator privileges. It's not only a security risk, but it also messes up paths resolution (execution path should never point to ``Windows\system32``).

Maybe try running SB like a regular program and it should behave normally. If you use a shortcut, check that the starting path is your SB installation path.

**Comment by Sehelitar** [comment]
I guess it worked. Closing this for now.
