### ISSUE TITLE
[Request] Host/Raid Triggers.

### ISSUE THREAD

**Issue by Jyojibh** [Sehelitar/Kick.bot#25]
As the title indicates.

As you can have a trigger that sets off a Follow or Sub could a Host/Raid be implemented ? 

![image](https://github.com/Sehelitar/Kick.bot/assets/8933677/5c2dff59-4660-472d-bfec-ed3bfc7eaecd)

**Comment by mocchimon** [comment]
it's on the bottom of your kick section

**Comment by Jyojibh** [comment]
> it's on the bottom of your kick section [Kick] Raid

I'm blind! Holy hell! Thanks.
