### ISSUE TITLE
[Issue] Timed Actions Not Triggering Actions

### ISSUE THREAD

**Issue by Jyojibh** [Sehelitar/Kick.bot#30]
I have a timed Action for a command and it does not trigger the command after X amount of lines of codes.

Not sure if this is not yet implemented or if this is a bug?

**Comment by mocchimon** [comment]
What line of codes are you speaking of and do you have a screen shot?

**Comment by Sehelitar** [comment]
Native timed actions are not supported because they don't know anything about Kick (if you use the "lines" parameter, actions solely based on an interval should work though).
It might be possible to handle them with a custom implementation using the same technique I used for commands.
