### ISSUE TITLE
Raid not displaying the right user

### ISSUE THREAD

**Issue by mocchimon** [Sehelitar/Kick.bot#34]
whenever I use the raid trigger the wrong person is listed under user. For example when someone would raid me instead of the user that raided me is displayed, my name would instead
![image](https://github.com/Sehelitar/Kick.bot/assets/10341644/48e598c0-ab6e-47e6-8930-b0534fefbd1f)

**Comment by mocchimon** [comment]
![image](https://github.com/Sehelitar/Kick.bot/assets/10341644/cee75b6b-4815-4da0-8c10-a252ed778840)
Seems to only happen in Discord webhook sadly

**Comment by Sehelitar** [comment]
Hi!
When you inspect variables, are the arguments set right or not ?
<img width="281" alt="image" src="https://github.com/Sehelitar/Kick.bot/assets/1716704/2562de2c-990c-42cf-8337-29288d2f6c8f">

I made a small change in the latest update that might help a little.
This event is really hard for me to implement. I don't have proper informations to work with and it's a lot of guess-work.

**Comment by mocchimon** [comment]
For follows, gifted subs, and subs work correctly just not raids.
![image](https://github.com/Sehelitar/Kick.bot/assets/10341644/2cbf1822-3e82-430c-948d-d3ae70709d71)

**Comment by mocchimon** [comment]
I don't have the action queue for it anymore. I'll get back to you on it but I have raids, gifted subs, subs, and follows setup the same way

**Comment by mocchimon** [comment]
as of the latest update 3.10 raids + webhooks no longer work for me

**Comment by mocchimon** [comment]
Before 0.3.10: the raid trigger was was working correct but was giving me the wrong username of the person who raided me. Discord webhooks was reporting that I raided my self. 

After 0.3.10: The raid trigger no longer works

**Comment by Sehelitar** [comment]
Ok, I think I found out what I was missing. This should be fixed in the next update!
