### ISSUE TITLE
[Request] Account Age

### ISSUE THREAD

**Issue by Jyojibh** [Sehelitar/Kick.bot#37]
Another request,

As you can see from below when you go to the V2 API page for instance mine below. You can see from the screen shot it gives a value of the date your account was created.

However when you try to use %accountAge% it currently shows the value of  the second screenshot. Is their a way to update this to show as a date format?

https://kick.com/api/v2/channels/Jyojibh 

![image](https://github.com/Sehelitar/Kick.bot/assets/8933677/7d61441b-0ff8-4003-89bf-a7057193cd63)

![image](https://github.com/Sehelitar/Kick.bot/assets/8933677/cc1e48f8-ca46-4e6a-8272-a0b569651bb6)

**Comment by Sehelitar** [comment]
This is set like this to match the Twitch-equivalent method from SB. This way, it's easier for people with existing Twitch actions to reuse them with Kick. It's still possible to instanciate a DateTime object from this value, so it's possible to format it in any form you want with a little bit of code.

https://wiki.streamer.bot/en/Sub-Actions/Twitch/Get-User-Info-for-Target
<img width="291" alt="image" src="https://github.com/Sehelitar/Kick.bot/assets/1716704/c064218c-4d4c-434b-9d36-5f32395f6856">
