### ISSUE TITLE
[REQUEST] name and message from "Chat Message Deleted".

### ISSUE THREAD

**Issue by MaddestScience** [Sehelitar/Kick.bot#39]
Hi,

I'm sending all moderator actions towards discord on twitch.
For Kick, by using your plugin, i'm able to send Bans and Timeouts to discord.
But i cant seem to handle send messages like i hoped.
Is there a possibility to add the name of the message sender, and the message to the "Chat Message Deleted" trigger?
And eventually, if it's possible, the moderator that deleted the message?

Thanks for your hard work! 

Regards,
Mark

**Comment by Sehelitar** [comment]
Hi! 👋

When a message is deleted, the only information we get is the Message ID, and nothing else. So : 
* it's impossible to know which moderator deleted the message.
* but it could be possible to get message details, but this requires to store messages history somewhere and get the data from there when this event occurs. I'll keep that as a possible future evolution.
