### ISSUE TITLE
[BUG] Version 0.3.11 Methods missing still ?

### ISSUE THREAD

**Issue by Jyojibh** [Sehelitar/Kick.bot#41]
I hate to be that person...

But I think the recent version you pushed out didnt add the methods again?

I cant see GetClips, GetFollowAgeInfo or PickRandomActiveUser  

![image](https://github.com/Sehelitar/Kick.bot/assets/8933677/dde7d399-4621-43f9-9f51-26488cb19506)

**Comment by Sehelitar** [comment]
I triple checked it and it's there.
Did you reimport the latest actions.txt file?
You're not the first one to report that, so I added SBActions.cs file to the project, you can copy/paste the action code from here : https://raw.githubusercontent.com/Sehelitar/Kick.bot/main/SBActions.cs

**Comment by Jyojibh** [comment]
Yeah, Just double checked! 

I re-installed it completely from scratch remove the kickbot action itself and re-installed it, Seemed to have worked... weird honestly. Thanks for the check though!
