### ISSUE TITLE
[Request] GetTargetUserInfo

### ISSUE THREAD

**Issue by Jyojibh** [Sehelitar/Kick.bot#44]
Currently when you do the method GetUsersInfo its the person that typed out the command, However can we get the TargetUserInfo? 

I would like the ability to draw the last thing a person was playing and other details instead of the person that triggered it

https://wiki.streamer.bot/en/Sub-Actions/Twitch/Get-User-Info-for-Target

**Comment by MaddestScience** [comment]
I guess when you do make an targeted command, and add an argument in streamerbot called user, give it the value of %input0% 
It will grab the GetUsersInfo from the %input0% 
Try that.

**Comment by Jyojibh** [comment]
This is how I currently have it setup but I am still adding to it, But It doesn't seem to give the targeted user's details just mine.

I did try the other way around so having Execute GetUserInfos after the Argument as well as i wasnt sure which way around it should be but it didnt work out.

I also tried setting user to %rawInput% as well, And that doesnt seem to work, So a little stumped

![image](https://github.com/Sehelitar/Kick.bot/assets/8933677/92b86041-409c-43e9-9e46-03024e7872be)

**Comment by Sehelitar** [comment]
Use ``%targetUser%`` which is way more reliable than ``%user%`` (since it is already set with your own info).

<img width="400" alt="image" src="https://github.com/Sehelitar/Kick.bot/assets/1716704/3b856deb-e212-4b24-b813-eaad67679ed0">

**Comment by Jyojibh** [comment]
That worked perfectly, I wondered if it was that simple but thought id double check :)
