### ISSUE TITLE
[BUG] Timed Actions

### ISSUE THREAD

**Issue by Jyojibh** [Sehelitar/Kick.bot#45]
Not sure if its an overall killing feature, As it works for me either way.

But when you do Random tickbox for the Timed Action it will not trigger.

I tried doing 2 lines with between 1 - 5 seconds and it wouldnt trigger no matter what, But if you put down a solid seconds it will trigger.

**Comment by Sehelitar** [comment]
I tried every possible combination and it works perfectly fine. Is there anything in the logs?
Check for any error/exception that is related to Kick or LiteDB.

**Comment by Jyojibh** [comment]
Damn... Its making me out to be a liar! I just double checked it after helping a friend re-install it and tried to recreate it again and now it works.. So consider this closed. I checked the log from the other day and it just says when it triggered from one event set.

`[2024-03-12 12:41:18.315 INF] [Kick] 2 timed action found`
`[2024-03-12 12:41:18.315 INF] [Kick] Resetting timed action "Discord" (ID 063861f9-1172-4964-88fb-720b8280fcac)`
`[2024-03-12 12:41:18.315 INF] [Kick] Resetting timed action "Follow" (ID e447b456-42b1-4d99-a821-e0075c971f1d)`
`[2024-03-12 12:41:19.146 DBG] Actions :: Time to save 3.5055ms`

`[2024-03-13 18:17:20.904 INF] [Kick] 2 timed action found`
`[2024-03-13 18:17:20.904 INF] [Kick] Resetting timed action "Discord" (ID 063861f9-1172-4964-88fb-720b8280fcac)`
`[2024-03-13 18:17:20.904 INF] [Kick] Resetting timed action "Follow" (ID e447b456-42b1-4d99-a821-e0075c971f1d)`
`[2024-03-13 18:17:24.868 INF] [Kick] Timed action "Discord" (ID 063861f9-1172-4964-88fb-720b8280fcac) triggered!`
`[2024-03-13 18:17:24.874 DBG] ActionDispatcher :: Queueing 'Discord' (f709adda-d3bf-4051-b04d-fbd612c79456) to 'Default`
`(00000000-0000-0000-0000-000000000000), with 7 arguments`

**Comment by Sehelitar** [comment]
I've been a software engineer long enough to see a lot of weird things 😅
If this happens again, check the logs for a ``Timed action "XXX" (ID <GUID>) triggered!`` message or any error that might point to the right direction.
I'll close this for now 👌
