### ISSUE TITLE
[request] trigger on "add vip" and "add of" and possibly "delete" of both?

### ISSUE THREAD

**Issue by MaddestScience** [Sehelitar/Kick.bot#47]
Hi,
Is it possible to add triggers for add/delete vip and og?

**Comment by Sehelitar** [comment]
Hi! 👋
Kick's events feed doesn't provide a way to listen to these actions, so I'm afraid it's not possible.

**Comment by MaddestScience** [comment]
bummer, but what can't be done. can't be done.
