### ISSUE TITLE
Connection + Reading commands

### ISSUE THREAD

**Issue by LordGrym** [Sehelitar/Kick.bot#5]
Yo! First of all, thanks for making this for Streamerbot. 

I managed to hook it up yesterday and the login window opened and I logged in all okay. But now going back into Streamerbot today to start setting up commands. 

Just looking for a little guidance on the commands firing. Not too familiar with C# but I think I have it set up right. Please see the images attached. Code compiled all good and even set the KickBot.dll and Kick.dll in the Refs just in case. I have tested the command both by right clicking the trigger and also typing !merch in chat. Should return "Test Message" but I get nothing.

Is there a way to tell if it's still connected to my Kick account / chat? Loading SB doesn't bring up any login screen for Kick. So I assume it's still connected or authenticated. Might be something simple I have missed here, please let me know. Cheers!

![KickCommand1](https://github.com/Sehelitar/Kick.bot/assets/73262274/ac576149-1423-40e6-b14d-87cd359f75a0)
![KickCommand2](https://github.com/Sehelitar/Kick.bot/assets/73262274/ebe69c23-77e6-4bba-82c5-2754f31ecc59)

**Comment by Sehelitar** [comment]
Hi!

Everytime you launch Streamer.bot, a Windows notification should pop up like this :

<img width="283" alt="image" src="https://github.com/Sehelitar/Kick.bot/assets/1716704/93c50119-f4bc-4488-a52a-5342a63e805b">

If it doesn't, check if your Windows notifications are muted, or check Streamer.bot logs to see if there's any error.

To set the ``message`` argument, you don't need to use C# code. Just use the ``Set Argument`` sub-action like this : 

<img width="389" alt="image" src="https://github.com/Sehelitar/Kick.bot/assets/1716704/42fb9b36-0c0e-4278-9d32-86a2c1c09644">

Write your message :

<img width="246" alt="image" src="https://github.com/Sehelitar/Kick.bot/assets/1716704/f4ee5545-9330-4267-89cd-9d4400352fd7">

Then send it :

<img width="286" alt="image" src="https://github.com/Sehelitar/Kick.bot/assets/1716704/e6738cc9-008d-47fb-8626-8dfe2ba150be">

Sub-actions order is important. Remember to set your arguments BEFORE calling any C# method.
It should work now 😄 

### Bonus

Now, if you want to know how to use C# code to do it that way, just use ``CPH.SetArgument`` like this :

<img width="600" alt="image" src="https://github.com/Sehelitar/Kick.bot/assets/1716704/97ea9f5a-e4d2-4a99-9570-4ee9e9fe8632">

You don't need any reference at all, just put the code sub-action before the method call like this : 

<img width="202" alt="image" src="https://github.com/Sehelitar/Kick.bot/assets/1716704/13838dc6-8579-449a-b0b4-a9897a8870bb">

**Comment by LordGrym** [comment]
You're a legend mate, thanks for this. Will give it a whirl in a moment. Appreciate it!

**Comment by LordGrym** [comment]
Can confirm it all works. Had the windows notifications muted lol. Thanks man. Is there any way - or any plans on having a different account (bot account) send the messages? Might be a tricky one I imagine. Either way this works a treat, thanks again!

**Comment by Sehelitar** [comment]
Thank you, I'm really glad you like it 😊 

It's way too complicated to have both account connected for now, their public API will make this a lot easier.
BUT, with that said, you can actually use a bot account if you want.

You need to create a Kick account for your bot, make it a mod on your channel, connect this extension with your bot account, then modify the C# code like this :

<img width="531" alt="image" src="https://github.com/Sehelitar/Kick.bot/assets/1716704/aab74cab-89df-4b6b-941e-7b33e76a80e1">

That way, the bot will connect to your own channel through the bot account.

To disconnect your currently connected account, close Streamer.bot and delete this folder ``Streamer.bot.exe.WebView2``. Don't worry, it's safe to delete it. The login window will show up then.

**Comment by LordGrym** [comment]
Worked perfectly. Thanks a ton!

**Comment by JotaRodriii** [comment]
Good evening,

Could you explain me how you have assigned a kick command to a message sent from streamer.bot?

Even if I save or reload streamer.bot it always comes up with Any

Thanks!

**Comment by LordGrym** [comment]
Hi there

Not sure if you are still needing assistance in setting this up for streamerbot. But here are some screenshots that might help

Just make sure you have those DLL refs setup properly and that your account - or bot account is logging in

Then you can set up these actions to send messages, and of course a trigger in the [COMMANDS] tab to link it up.

Hopefully that helps and you can sort it out!


[cid:f8ef6c1a-04b3-4b98-8a4b-2ae719761622]
Just so you know, the reason why I have put my channel name "grym" in the code above is because at initial setup / import of the bot I logged into my Bot account. Then pointed the account to connect to my main channel. Then your bot account can send all these messages.


[cid:15d1423d-6382-4be5-aa92-720703286054]

[cid:0e63007a-ce9c-43ba-9434-bb590cc68f8c]
________________________________
