### ISSUE TITLE
Fatal UI Error on launch 

### ISSUE THREAD

**Issue by stoutimon** [Sehelitar/Kick.bot#53]
[log_20240503.log](https://github.com/Sehelitar/Kick.bot/files/15201292/log_20240503.log)
I keep getting a fatal UI error on launching streamerbot. seems the kick.bot extension is causing the issue. Should I wait for an update or is there a fix?
Any advice is highly appreciated.
![SB UI Exception](https://github.com/Sehelitar/Kick.bot/assets/151385386/0af73acf-4e73-4b21-9858-97c0fec44642)

**Comment by Sehelitar** [comment]
Hi! 👋 
By looking at your logs I can say that Pusher's DLLs are missing.
Are you sure you copy/pasted all the DLLs from the archive into the ``dlls`` folder of the bot?

**Comment by stoutimon** [comment]
I may have overlooked that. I will try again. Thank you for the info, much appreciated.
