### ISSUE TITLE
Output/Display Kick Chat in Chat window?

### ISSUE THREAD

**Issue by OikoumE** [Sehelitar/Kick.bot#54]
Hi, i was thinking, would it be possible to output the chat to the chat window?
im assuming you have to read the chat and have access to send messages, and it would be great if we could display the chat  together with the other platforms and not having to have kick out as its own chat. i was hoping this was possible and is why i installed the plugin

thanks for you work!

**Comment by Sehelitar** [comment]
Hi! 👋 
Streamer.bot does not provide any way for devs to integrate their own custom platform, and AFAIK this is not something even planned yet. So unless they add this possibility, I can't integrate Kick to the embeded chat window 😭

**Comment by OikoumE** [comment]
fair enough :D i eventually found a solution (third party)
