### ISSUE TITLE
HELP (Anyone can help me with this problem)

### ISSUE THREAD

**Issue by urkoperez16** [Sehelitar/Kick.bot#56]
Its my first time using Streamer.bot and I don't know how it works and I don't know how to integrate this plugin for kick too.
if someone could help me I would be very grateful (sorry for my bad English)

**Comment by mocchimon** [comment]
This is the wrong place for this. try https://github.com/Sehelitar/Kick.bot/discussions

**Comment by urkoperez16** [comment]
I still don't know how it works

**Comment by mocchimon** [comment]
that isn't an issue. This section is for reporting issues. There's a discussion page and a tutorial on my main page
