### ISSUE TITLE
GetUserInfos not collecting the right target

### ISSUE THREAD

**Issue by mocchimon** [Sehelitar/Kick.bot#6]
Hi,

Amazing work on getting stream bot to work with kick. I've been having issues with trying to get manual shoutout's to work. Attached is how I have it setup but the target keeps targeting my instead of the user I'm trying to shoutout

**Comment by Sehelitar** [comment]
Hi!

Which trigger do you use to run this action ?
If you use a command like ``!so <Shoutout target>``, you'll need to add a "Set Argument" sub-action before the call to GetUserInfos, and set ``targetUser`` => ``%rawInput%``

This is what it should look like:
![image](https://github.com/Sehelitar/Kick.bot/assets/1716704/1f194b8b-62d0-4ec1-8613-4da3abec11bd)

**I also published a hotfix that could be useful for you a few minutes ago.**
This fix is required to make this example work => https://github.com/Sehelitar/Kick.bot/releases/latest

**Comment by mocchimon** [comment]
I was using the same trigger while on v3.5.0. I'll give it a try again on the latest  update and get back.
![image](https://github.com/Sehelitar/Kick.bot/assets/10341644/d4f97c5f-3d7f-4ea5-90eb-bf031a43f72d)

**Comment by mocchimon** [comment]
Got everything working on 3.5.1 but for some reason target gets lost for find game and channel title
![image](https://github.com/Sehelitar/Kick.bot/assets/10341644/1bebcff7-8180-4455-bc09-621a65d4bff3)

![image](https://github.com/Sehelitar/Kick.bot/assets/10341644/30d66835-7869-4cdb-9d55-37b079158eb2)

**Comment by Sehelitar** [comment]
Can you try without the @ in the username ?
This is something I might filter out in a future update, but for now, the @ is not ignored, that might explain why.

**Comment by mocchimon** [comment]
without the @ works fine

**Comment by Sehelitar** [comment]
I just published a new hotfix to filter out any leading @ in usernames, so you won't have to worry about it anymore :)
Also, thank you for the donation, it's really appreciated 😍

https://github.com/Sehelitar/Kick.bot/releases/latest
