### ISSUE TITLE
I can't get anything to work

### ISSUE THREAD

**Issue by Cadiz3D** [Sehelitar/Kick.bot#86]
I have installed it, compiled the code, the kick login page opens, I log in to it, it tells me that I have logged in correctly, but it never closes. Every time I start streamer.bot the logged in window opens and stays open all the time. I have tried several plugins but none of them work. Please help me, I would like to be able to use this extension in my live streams but I can't.

**Comment by ohckan** [comment]
Try enabling kick's two-step verification, it worked for me and I had the same problem

**Comment by Cadiz3D** [comment]
Thank you very much my friend, that was it, I'm going to try everything to see how it goes.
